// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"gozerodemo/source2go/userRpc/example/proto/greet"
	"gozerodemo/source2go/userRpc/internal/logic"
	"gozerodemo/source2go/userRpc/internal/svc"
)

type GreetServer struct {
	svcCtx *svc.ServiceContext
	greet.UnimplementedGreetServer
}

func NewGreetServer(svcCtx *svc.ServiceContext) *GreetServer {
	return &GreetServer{
		svcCtx: svcCtx,
	}
}

// 定义客户端流式 rpc
func (s *GreetServer) SendMessage(stream greet.Greet_SendMessageServer) error {
	l := logic.NewSendMessageLogic(stream.Context(), s.svcCtx)
	return l.SendMessage(stream)
}
