// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: aorange.proto

package aorange

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Aorange_Ping_FullMethodName = "/aorange.Aorange/Ping"
)

// AorangeClient is the client API for Aorange service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AorangeClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type aorangeClient struct {
	cc grpc.ClientConnInterface
}

func NewAorangeClient(cc grpc.ClientConnInterface) AorangeClient {
	return &aorangeClient{cc}
}

func (c *aorangeClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Aorange_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AorangeServer is the server API for Aorange service.
// All implementations must embed UnimplementedAorangeServer
// for forward compatibility.
type AorangeServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedAorangeServer()
}

// UnimplementedAorangeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAorangeServer struct{}

func (UnimplementedAorangeServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAorangeServer) mustEmbedUnimplementedAorangeServer() {}
func (UnimplementedAorangeServer) testEmbeddedByValue()                 {}

// UnsafeAorangeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AorangeServer will
// result in compilation errors.
type UnsafeAorangeServer interface {
	mustEmbedUnimplementedAorangeServer()
}

func RegisterAorangeServer(s grpc.ServiceRegistrar, srv AorangeServer) {
	// If the following call panics, it indicates UnimplementedAorangeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Aorange_ServiceDesc, srv)
}

func _Aorange_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AorangeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aorange_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AorangeServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Aorange_ServiceDesc is the grpc.ServiceDesc for Aorange service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Aorange_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aorange.Aorange",
	HandlerType: (*AorangeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Aorange_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aorange.proto",
}
