// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: aorange.proto

package server

import (
	"context"

	"gozerodemo/aorange/aorange"
	"gozerodemo/aorange/internal/logic"
	"gozerodemo/aorange/internal/svc"
)

type AorangeServer struct {
	svcCtx *svc.ServiceContext
	aorange.UnimplementedAorangeServer
}

func NewAorangeServer(svcCtx *svc.ServiceContext) *AorangeServer {
	return &AorangeServer{
		svcCtx: svcCtx,
	}
}

func (s *AorangeServer) Ping(ctx context.Context, in *aorange.Request) (*aorange.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
