// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: addsrv.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AddSrv_Add_FullMethodName    = "/proto.AddSrv/Add"
	AddSrv_Concat_FullMethodName = "/proto.AddSrv/Concat"
)

// AddSrvClient is the client API for AddSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddSrvClient interface {
	Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error)
	Concat(ctx context.Context, in *ConcatReq, opts ...grpc.CallOption) (*ConcatResp, error)
}

type addSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewAddSrvClient(cc grpc.ClientConnInterface) AddSrvClient {
	return &addSrvClient{cc}
}

func (c *addSrvClient) Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResp)
	err := c.cc.Invoke(ctx, AddSrv_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addSrvClient) Concat(ctx context.Context, in *ConcatReq, opts ...grpc.CallOption) (*ConcatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConcatResp)
	err := c.cc.Invoke(ctx, AddSrv_Concat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddSrvServer is the server API for AddSrv service.
// All implementations must embed UnimplementedAddSrvServer
// for forward compatibility.
type AddSrvServer interface {
	Add(context.Context, *AddReq) (*AddResp, error)
	Concat(context.Context, *ConcatReq) (*ConcatResp, error)
	mustEmbedUnimplementedAddSrvServer()
}

// UnimplementedAddSrvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAddSrvServer struct{}

func (UnimplementedAddSrvServer) Add(context.Context, *AddReq) (*AddResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedAddSrvServer) Concat(context.Context, *ConcatReq) (*ConcatResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Concat not implemented")
}
func (UnimplementedAddSrvServer) mustEmbedUnimplementedAddSrvServer() {}
func (UnimplementedAddSrvServer) testEmbeddedByValue()                {}

// UnsafeAddSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddSrvServer will
// result in compilation errors.
type UnsafeAddSrvServer interface {
	mustEmbedUnimplementedAddSrvServer()
}

func RegisterAddSrvServer(s grpc.ServiceRegistrar, srv AddSrvServer) {
	// If the following call panics, it indicates UnimplementedAddSrvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AddSrv_ServiceDesc, srv)
}

func _AddSrv_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddSrvServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddSrv_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddSrvServer).Add(ctx, req.(*AddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddSrv_Concat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConcatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddSrvServer).Concat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddSrv_Concat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddSrvServer).Concat(ctx, req.(*ConcatReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AddSrv_ServiceDesc is the grpc.ServiceDesc for AddSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AddSrv",
	HandlerType: (*AddSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _AddSrv_Add_Handler,
		},
		{
			MethodName: "Concat",
			Handler:    _AddSrv_Concat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "addsrv.proto",
}
