// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"gozeroservicedemo/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/order/:orderSn",
				Handler: detailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/create",
				Handler: createHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/order/delete",
				Handler: deleteHandler(serverCtx),
			},
		},
	)
}
