// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: addsrv.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReq) Reset() {
	*x = AddReq{}
	mi := &file_addsrv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReq) ProtoMessage() {}

func (x *AddReq) ProtoReflect() protoreflect.Message {
	mi := &file_addsrv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReq.ProtoReflect.Descriptor instead.
func (*AddReq) Descriptor() ([]byte, []int) {
	return file_addsrv_proto_rawDescGZIP(), []int{0}
}

func (x *AddReq) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *AddReq) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type AddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sum           int32                  `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResp) Reset() {
	*x = AddResp{}
	mi := &file_addsrv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResp) ProtoMessage() {}

func (x *AddResp) ProtoReflect() protoreflect.Message {
	mi := &file_addsrv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResp.ProtoReflect.Descriptor instead.
func (*AddResp) Descriptor() ([]byte, []int) {
	return file_addsrv_proto_rawDescGZIP(), []int{1}
}

func (x *AddResp) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *AddResp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type ConcatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B             string                 `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcatReq) Reset() {
	*x = ConcatReq{}
	mi := &file_addsrv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcatReq) ProtoMessage() {}

func (x *ConcatReq) ProtoReflect() protoreflect.Message {
	mi := &file_addsrv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcatReq.ProtoReflect.Descriptor instead.
func (*ConcatReq) Descriptor() ([]byte, []int) {
	return file_addsrv_proto_rawDescGZIP(), []int{2}
}

func (x *ConcatReq) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *ConcatReq) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

type ConcatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           string                 `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcatResp) Reset() {
	*x = ConcatResp{}
	mi := &file_addsrv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcatResp) ProtoMessage() {}

func (x *ConcatResp) ProtoReflect() protoreflect.Message {
	mi := &file_addsrv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcatResp.ProtoReflect.Descriptor instead.
func (*ConcatResp) Descriptor() ([]byte, []int) {
	return file_addsrv_proto_rawDescGZIP(), []int{3}
}

func (x *ConcatResp) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

func (x *ConcatResp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_addsrv_proto protoreflect.FileDescriptor

const file_addsrv_proto_rawDesc = "" +
	"\n" +
	"\faddsrv.proto\x12\x05proto\"$\n" +
	"\x06AddReq\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x05R\x01b\"-\n" +
	"\aAddResp\x12\x10\n" +
	"\x03sum\x18\x01 \x01(\x05R\x03sum\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\"'\n" +
	"\tConcatReq\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\tR\x01b\"0\n" +
	"\n" +
	"ConcatResp\x12\x10\n" +
	"\x03res\x18\x01 \x01(\tR\x03res\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err2]\n" +
	"\x06AddSrv\x12$\n" +
	"\x03Add\x12\r.proto.AddReq\x1a\x0e.proto.AddResp\x12-\n" +
	"\x06Concat\x12\x10.proto.ConcatReq\x1a\x11.proto.ConcatRespB\x13Z\x11gokitaddsrv/protob\x06proto3"

var (
	file_addsrv_proto_rawDescOnce sync.Once
	file_addsrv_proto_rawDescData []byte
)

func file_addsrv_proto_rawDescGZIP() []byte {
	file_addsrv_proto_rawDescOnce.Do(func() {
		file_addsrv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_addsrv_proto_rawDesc), len(file_addsrv_proto_rawDesc)))
	})
	return file_addsrv_proto_rawDescData
}

var file_addsrv_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_addsrv_proto_goTypes = []any{
	(*AddReq)(nil),     // 0: proto.AddReq
	(*AddResp)(nil),    // 1: proto.AddResp
	(*ConcatReq)(nil),  // 2: proto.ConcatReq
	(*ConcatResp)(nil), // 3: proto.ConcatResp
}
var file_addsrv_proto_depIdxs = []int32{
	0, // 0: proto.AddSrv.Add:input_type -> proto.AddReq
	2, // 1: proto.AddSrv.Concat:input_type -> proto.ConcatReq
	1, // 2: proto.AddSrv.Add:output_type -> proto.AddResp
	3, // 3: proto.AddSrv.Concat:output_type -> proto.ConcatResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_addsrv_proto_init() }
func file_addsrv_proto_init() {
	if File_addsrv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_addsrv_proto_rawDesc), len(file_addsrv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_addsrv_proto_goTypes,
		DependencyIndexes: file_addsrv_proto_depIdxs,
		MessageInfos:      file_addsrv_proto_msgTypes,
	}.Build()
	File_addsrv_proto = out.File
	file_addsrv_proto_goTypes = nil
	file_addsrv_proto_depIdxs = nil
}
