// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: user.proto

// proto 包名

package greet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Greet_SendMessage_FullMethodName = "/greet.Greet/SendMessage"
)

// GreetClient is the client API for Greet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义 Greet 服务
type GreetClient interface {
	// 定义客户端流式 rpc
	SendMessage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendMessageReq, SendMessageResp], error)
}

type greetClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetClient(cc grpc.ClientConnInterface) GreetClient {
	return &greetClient{cc}
}

func (c *greetClient) SendMessage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendMessageReq, SendMessageResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Greet_ServiceDesc.Streams[0], Greet_SendMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendMessageReq, SendMessageResp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Greet_SendMessageClient = grpc.ClientStreamingClient[SendMessageReq, SendMessageResp]

// GreetServer is the server API for Greet service.
// All implementations must embed UnimplementedGreetServer
// for forward compatibility.
//
// 定义 Greet 服务
type GreetServer interface {
	// 定义客户端流式 rpc
	SendMessage(grpc.ClientStreamingServer[SendMessageReq, SendMessageResp]) error
	mustEmbedUnimplementedGreetServer()
}

// UnimplementedGreetServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGreetServer struct{}

func (UnimplementedGreetServer) SendMessage(grpc.ClientStreamingServer[SendMessageReq, SendMessageResp]) error {
	return status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedGreetServer) mustEmbedUnimplementedGreetServer() {}
func (UnimplementedGreetServer) testEmbeddedByValue()               {}

// UnsafeGreetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetServer will
// result in compilation errors.
type UnsafeGreetServer interface {
	mustEmbedUnimplementedGreetServer()
}

func RegisterGreetServer(s grpc.ServiceRegistrar, srv GreetServer) {
	// If the following call panics, it indicates UnimplementedGreetServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Greet_ServiceDesc, srv)
}

func _Greet_SendMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServer).SendMessage(&grpc.GenericServerStream[SendMessageReq, SendMessageResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Greet_SendMessageServer = grpc.ClientStreamingServer[SendMessageReq, SendMessageResp]

// Greet_ServiceDesc is the grpc.ServiceDesc for Greet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greet.Greet",
	HandlerType: (*GreetServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMessage",
			Handler:       _Greet_SendMessage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "user.proto",
}
