// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderFieldNames          = builder.RawFieldNames(&Order{})
	orderRows                = strings.Join(orderFieldNames, ",")
	orderRowsExpectAutoSet   = strings.Join(stringx.Remove(orderFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	orderRowsWithPlaceHolder = strings.Join(stringx.Remove(orderFieldNames, "`order_sn`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheOrderOrderSnPrefix = "cache:order:orderSn:"
)

type (
	orderModel interface {
		Insert(ctx context.Context, data *Order) (sql.Result, error)
		FindOne(ctx context.Context, orderSn string) (*Order, error)
		Update(ctx context.Context, data *Order) error
		Delete(ctx context.Context, orderSn string) error
	}

	defaultOrderModel struct {
		sqlc.CachedConn
		table string
	}

	Order struct {
		OrderSn  string       `db:"order_sn"`  // 订单号
		UserId   int64        `db:"user_id"`   // 用户ID
		GoodsId  int64        `db:"goods_id"`  // 商品ID
		Num      int64        `db:"num"`       // 数量
		Amount   int64        `db:"amount"`    // 金额
		Status   int64        `db:"status"`    // 状态
		CreateAt time.Time    `db:"create_at"` // 创建时间
		DeleteAt sql.NullTime `db:"delete_at"` // 删除时间
	}
)

func newOrderModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOrderModel {
	return &defaultOrderModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`order`",
	}
}

func (m *defaultOrderModel) Delete(ctx context.Context, orderSn string) error {
	orderOrderSnKey := fmt.Sprintf("%s%v", cacheOrderOrderSnPrefix, orderSn)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `order_sn` = ?", m.table)
		return conn.ExecCtx(ctx, query, orderSn)
	}, orderOrderSnKey)
	return err
}

func (m *defaultOrderModel) FindOne(ctx context.Context, orderSn string) (*Order, error) {
	orderOrderSnKey := fmt.Sprintf("%s%v", cacheOrderOrderSnPrefix, orderSn)
	var resp Order
	err := m.QueryRowCtx(ctx, &resp, orderOrderSnKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `order_sn` = ? limit 1", orderRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, orderSn)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderModel) Insert(ctx context.Context, data *Order) (sql.Result, error) {
	orderOrderSnKey := fmt.Sprintf("%s%v", cacheOrderOrderSnPrefix, data.OrderSn)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, orderRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.OrderSn, data.UserId, data.GoodsId, data.Num, data.Amount, data.Status, data.DeleteAt)
	}, orderOrderSnKey)
	return ret, err
}

func (m *defaultOrderModel) Update(ctx context.Context, data *Order) error {
	orderOrderSnKey := fmt.Sprintf("%s%v", cacheOrderOrderSnPrefix, data.OrderSn)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `order_sn` = ?", m.table, orderRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.GoodsId, data.Num, data.Amount, data.Status, data.DeleteAt, data.OrderSn)
	}, orderOrderSnKey)
	return err
}

func (m *defaultOrderModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheOrderOrderSnPrefix, primary)
}

func (m *defaultOrderModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `order_sn` = ? limit 1", orderRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOrderModel) tableName() string {
	return m.table
}
