// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: aorange.proto

package aorangeclient

import (
	"context"

	"gozerodemo/aorange/aorange"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = aorange.Request
	Response = aorange.Response

	Aorange interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultAorange struct {
		cli zrpc.Client
	}
)

func NewAorange(cli zrpc.Client) Aorange {
	return &defaultAorange{
		cli: cli,
	}
}

func (m *defaultAorange) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := aorange.NewAorangeClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
