// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateReq struct {
	UserId  int64 `json:"userId"`
	GoodsId int64 `json:"goodsId"`
	Num     int64 `json:"num"`
	Amount  int64 `json:"amount"`
}

type CreateResp struct {
	OrderSn string `json:"orderSn"`
}

type DeleteReq struct {
	UserId  int64  `json:"userId"`
	OrderSn string `json:"orderSn"`
}

type DeleteResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type DetailReq struct {
	OrderSn string `json:"orderSn"`
}

type DetailResp struct {
	OrderSn  string `json:"orderSn"`
	UserId   int64  `json:"userId"`
	GoodsId  int64  `json:"goodsid"`
	Num      int64  `json:"num"`
	Amount   int64  `json:"amount"`
	Status   int64  `json:"status"`
	CreateAt string `json:"createAt"`
}
