// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginReq struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type RegisterReq struct {
	UserName   string `json:"username"`
	Password   string `json:"password"`
	Repassword string `json:"re_password"`
	Mobile     string `json:"mobile"`
	Gender     int    `json:"gender,options=0|1|2,default=0"` // male|female|unknown
	NickName   string `json:"nickname"`
}

type RegisterResp struct {
	Success bool   `json:"success"` // 注册是否成功
	Message string `json:"message"` // 注册报错信息
	Id      int64  `json:"id"`      // 成功注册返回的 id
}

type UserInfoReq struct {
	Id    int64 `json:"id"`
	Token int64 `json:"token"`
}

type UserInfoResp struct {
	Id       int64  `json:"id"`
	Token    string `json:"token"`
	UserName string `json:"username"`
	Mobile   string `json:"mobile"`
	Gender   string `json:"gender"`
	NickName string `json:"nickname"`
	CreateAt string `json:"createAt"` // 注册时间
	UpdateAt string `json:"updateAt"` // 最后更新时间
}

type UserUpdateReq struct {
	Id       int64  `json:"id"`
	UserName string `json:"username"`
	Password string `json:"password"`
	Mobile   string `json:"mobile"`
	Gender   string `json:"gender"` // male|female|unknown
	NickName string `json:"nickname"`
}

type UserUpdateResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"` // 更新报错信息
}
