// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pb/trim.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Trim方法的请求参数
type TrimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S             string                 `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrimRequest) Reset() {
	*x = TrimRequest{}
	mi := &file_pb_trim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrimRequest) ProtoMessage() {}

func (x *TrimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_trim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrimRequest.ProtoReflect.Descriptor instead.
func (*TrimRequest) Descriptor() ([]byte, []int) {
	return file_pb_trim_proto_rawDescGZIP(), []int{0}
}

func (x *TrimRequest) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

// Trim方法的响应
type TrimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S             string                 `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrimResponse) Reset() {
	*x = TrimResponse{}
	mi := &file_pb_trim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrimResponse) ProtoMessage() {}

func (x *TrimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_trim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrimResponse.ProtoReflect.Descriptor instead.
func (*TrimResponse) Descriptor() ([]byte, []int) {
	return file_pb_trim_proto_rawDescGZIP(), []int{1}
}

func (x *TrimResponse) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

var File_pb_trim_proto protoreflect.FileDescriptor

const file_pb_trim_proto_rawDesc = "" +
	"\n" +
	"\rpb/trim.proto\x12\x02pb\"\x1b\n" +
	"\vTrimRequest\x12\f\n" +
	"\x01s\x18\x01 \x01(\tR\x01s\"\x1c\n" +
	"\fTrimResponse\x12\f\n" +
	"\x01s\x18\x01 \x01(\tR\x01s28\n" +
	"\x04Trim\x120\n" +
	"\tTrimSpace\x12\x0f.pb.TrimRequest\x1a\x10.pb.TrimResponse\"\x00B\x11Z\x0fgokittrimsrv/pbb\x06proto3"

var (
	file_pb_trim_proto_rawDescOnce sync.Once
	file_pb_trim_proto_rawDescData []byte
)

func file_pb_trim_proto_rawDescGZIP() []byte {
	file_pb_trim_proto_rawDescOnce.Do(func() {
		file_pb_trim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_trim_proto_rawDesc), len(file_pb_trim_proto_rawDesc)))
	})
	return file_pb_trim_proto_rawDescData
}

var file_pb_trim_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_trim_proto_goTypes = []any{
	(*TrimRequest)(nil),  // 0: pb.TrimRequest
	(*TrimResponse)(nil), // 1: pb.TrimResponse
}
var file_pb_trim_proto_depIdxs = []int32{
	0, // 0: pb.Trim.TrimSpace:input_type -> pb.TrimRequest
	1, // 1: pb.Trim.TrimSpace:output_type -> pb.TrimResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_trim_proto_init() }
func file_pb_trim_proto_init() {
	if File_pb_trim_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_trim_proto_rawDesc), len(file_pb_trim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_trim_proto_goTypes,
		DependencyIndexes: file_pb_trim_proto_depIdxs,
		MessageInfos:      file_pb_trim_proto_msgTypes,
	}.Build()
	File_pb_trim_proto = out.File
	file_pb_trim_proto_goTypes = nil
	file_pb_trim_proto_depIdxs = nil
}
